Majed Resume
saidiii111/majed-resume pull request #1
Opened 2018-02-20 12:54 UTC by saidiii111

2018-02-20 14:14 UTC, rabeedameer requested changes
"nice job but you need to take care of some fixes"

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +  <title>Majed-CV"</title>
"fix the Title Please"

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +
"You do not need all this space between elements"

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +
"the same as the former comment regarding space"

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +      <p>linux, git, HTML5, CSS</p>
It would be better if you use Abbreviations for CSS and HTML

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +    <p>&copy;coded by Said</p>
It is nice to use it and would be better if it contains other info about Majed ;)

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +</html>
you do not need a new line after </html>

2018-02-20 14:14 UTC, rabeedameer commented on index.htm
> +      <li> <a href="mailto:majedshrndan45@gmail.com?subject=feedback">email me</a> </li>
"try to fix this link please cuz you need to show the email not a link to it"

2018-02-21 14:13 UTC, saidiii111 commented
can y check it please?

2018-02-21 14:38 UTC, rabeedameer reviewed
some fixes

2018-02-21 14:38 UTC, rabeedameer commented on index.htm
> +      <li> <a href="mailto:majedshrndan45@gmail.com">email me</a> </li>
change "email me "

2018-02-21 14:38 UTC, rabeedameer commented on index.htm
> +    <p>&copy;coded by Said for Majed Shrndan</p>
sorry, you still need to change!

2018-02-21 14:41 UTC, rabeedameer approved these changes
Thanks for your efforts!

2018-02-21 14:41 UTC, merged